/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.skodjob.datagenerator.models.starwars;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StarWars extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1351044176025905925L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StarWars\",\"namespace\":\"io.skodjob.datagenerator.models.starwars\",\"fields\":[{\"name\":\"character_name\",\"type\":\"string\"},{\"name\":\"source_planet\",\"type\":\"string\"},{\"name\":\"target_planet\",\"type\":\"string\"},{\"name\":\"quote\",\"type\":\"string\"},{\"name\":\"callSign\",\"type\":\"string\"},{\"name\":\"species\",\"type\":\"string\"},{\"name\":\"vehicle\",\"type\":\"string\"},{\"name\":\"wookieWords\",\"type\":\"string\"},{\"name\":\"alternateCharacterSpelling\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StarWars> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StarWars> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StarWars> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StarWars> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StarWars> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StarWars to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StarWars from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StarWars instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StarWars fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence character_name;
  private java.lang.CharSequence source_planet;
  private java.lang.CharSequence target_planet;
  private java.lang.CharSequence quote;
  private java.lang.CharSequence callSign;
  private java.lang.CharSequence species;
  private java.lang.CharSequence vehicle;
  private java.lang.CharSequence wookieWords;
  private java.lang.CharSequence alternateCharacterSpelling;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StarWars() {}

  /**
   * All-args constructor.
   * @param character_name The new value for character_name
   * @param source_planet The new value for source_planet
   * @param target_planet The new value for target_planet
   * @param quote The new value for quote
   * @param callSign The new value for callSign
   * @param species The new value for species
   * @param vehicle The new value for vehicle
   * @param wookieWords The new value for wookieWords
   * @param alternateCharacterSpelling The new value for alternateCharacterSpelling
   */
  public StarWars(java.lang.CharSequence character_name, java.lang.CharSequence source_planet, java.lang.CharSequence target_planet, java.lang.CharSequence quote, java.lang.CharSequence callSign, java.lang.CharSequence species, java.lang.CharSequence vehicle, java.lang.CharSequence wookieWords, java.lang.CharSequence alternateCharacterSpelling) {
    this.character_name = character_name;
    this.source_planet = source_planet;
    this.target_planet = target_planet;
    this.quote = quote;
    this.callSign = callSign;
    this.species = species;
    this.vehicle = vehicle;
    this.wookieWords = wookieWords;
    this.alternateCharacterSpelling = alternateCharacterSpelling;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return character_name;
    case 1: return source_planet;
    case 2: return target_planet;
    case 3: return quote;
    case 4: return callSign;
    case 5: return species;
    case 6: return vehicle;
    case 7: return wookieWords;
    case 8: return alternateCharacterSpelling;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: character_name = (java.lang.CharSequence)value$; break;
    case 1: source_planet = (java.lang.CharSequence)value$; break;
    case 2: target_planet = (java.lang.CharSequence)value$; break;
    case 3: quote = (java.lang.CharSequence)value$; break;
    case 4: callSign = (java.lang.CharSequence)value$; break;
    case 5: species = (java.lang.CharSequence)value$; break;
    case 6: vehicle = (java.lang.CharSequence)value$; break;
    case 7: wookieWords = (java.lang.CharSequence)value$; break;
    case 8: alternateCharacterSpelling = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'character_name' field.
   * @return The value of the 'character_name' field.
   */
  public java.lang.CharSequence getCharacterName() {
    return character_name;
  }


  /**
   * Sets the value of the 'character_name' field.
   * @param value the value to set.
   */
  public void setCharacterName(java.lang.CharSequence value) {
    this.character_name = value;
  }

  /**
   * Gets the value of the 'source_planet' field.
   * @return The value of the 'source_planet' field.
   */
  public java.lang.CharSequence getSourcePlanet() {
    return source_planet;
  }


  /**
   * Sets the value of the 'source_planet' field.
   * @param value the value to set.
   */
  public void setSourcePlanet(java.lang.CharSequence value) {
    this.source_planet = value;
  }

  /**
   * Gets the value of the 'target_planet' field.
   * @return The value of the 'target_planet' field.
   */
  public java.lang.CharSequence getTargetPlanet() {
    return target_planet;
  }


  /**
   * Sets the value of the 'target_planet' field.
   * @param value the value to set.
   */
  public void setTargetPlanet(java.lang.CharSequence value) {
    this.target_planet = value;
  }

  /**
   * Gets the value of the 'quote' field.
   * @return The value of the 'quote' field.
   */
  public java.lang.CharSequence getQuote() {
    return quote;
  }


  /**
   * Sets the value of the 'quote' field.
   * @param value the value to set.
   */
  public void setQuote(java.lang.CharSequence value) {
    this.quote = value;
  }

  /**
   * Gets the value of the 'callSign' field.
   * @return The value of the 'callSign' field.
   */
  public java.lang.CharSequence getCallSign() {
    return callSign;
  }


  /**
   * Sets the value of the 'callSign' field.
   * @param value the value to set.
   */
  public void setCallSign(java.lang.CharSequence value) {
    this.callSign = value;
  }

  /**
   * Gets the value of the 'species' field.
   * @return The value of the 'species' field.
   */
  public java.lang.CharSequence getSpecies() {
    return species;
  }


  /**
   * Sets the value of the 'species' field.
   * @param value the value to set.
   */
  public void setSpecies(java.lang.CharSequence value) {
    this.species = value;
  }

  /**
   * Gets the value of the 'vehicle' field.
   * @return The value of the 'vehicle' field.
   */
  public java.lang.CharSequence getVehicle() {
    return vehicle;
  }


  /**
   * Sets the value of the 'vehicle' field.
   * @param value the value to set.
   */
  public void setVehicle(java.lang.CharSequence value) {
    this.vehicle = value;
  }

  /**
   * Gets the value of the 'wookieWords' field.
   * @return The value of the 'wookieWords' field.
   */
  public java.lang.CharSequence getWookieWords() {
    return wookieWords;
  }


  /**
   * Sets the value of the 'wookieWords' field.
   * @param value the value to set.
   */
  public void setWookieWords(java.lang.CharSequence value) {
    this.wookieWords = value;
  }

  /**
   * Gets the value of the 'alternateCharacterSpelling' field.
   * @return The value of the 'alternateCharacterSpelling' field.
   */
  public java.lang.CharSequence getAlternateCharacterSpelling() {
    return alternateCharacterSpelling;
  }


  /**
   * Sets the value of the 'alternateCharacterSpelling' field.
   * @param value the value to set.
   */
  public void setAlternateCharacterSpelling(java.lang.CharSequence value) {
    this.alternateCharacterSpelling = value;
  }

  /**
   * Creates a new StarWars RecordBuilder.
   * @return A new StarWars RecordBuilder
   */
  public static io.skodjob.datagenerator.models.starwars.StarWars.Builder newBuilder() {
    return new io.skodjob.datagenerator.models.starwars.StarWars.Builder();
  }

  /**
   * Creates a new StarWars RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StarWars RecordBuilder
   */
  public static io.skodjob.datagenerator.models.starwars.StarWars.Builder newBuilder(io.skodjob.datagenerator.models.starwars.StarWars.Builder other) {
    if (other == null) {
      return new io.skodjob.datagenerator.models.starwars.StarWars.Builder();
    } else {
      return new io.skodjob.datagenerator.models.starwars.StarWars.Builder(other);
    }
  }

  /**
   * Creates a new StarWars RecordBuilder by copying an existing StarWars instance.
   * @param other The existing instance to copy.
   * @return A new StarWars RecordBuilder
   */
  public static io.skodjob.datagenerator.models.starwars.StarWars.Builder newBuilder(io.skodjob.datagenerator.models.starwars.StarWars other) {
    if (other == null) {
      return new io.skodjob.datagenerator.models.starwars.StarWars.Builder();
    } else {
      return new io.skodjob.datagenerator.models.starwars.StarWars.Builder(other);
    }
  }

  /**
   * RecordBuilder for StarWars instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StarWars>
    implements org.apache.avro.data.RecordBuilder<StarWars> {

    private java.lang.CharSequence character_name;
    private java.lang.CharSequence source_planet;
    private java.lang.CharSequence target_planet;
    private java.lang.CharSequence quote;
    private java.lang.CharSequence callSign;
    private java.lang.CharSequence species;
    private java.lang.CharSequence vehicle;
    private java.lang.CharSequence wookieWords;
    private java.lang.CharSequence alternateCharacterSpelling;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.skodjob.datagenerator.models.starwars.StarWars.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.character_name)) {
        this.character_name = data().deepCopy(fields()[0].schema(), other.character_name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.source_planet)) {
        this.source_planet = data().deepCopy(fields()[1].schema(), other.source_planet);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.target_planet)) {
        this.target_planet = data().deepCopy(fields()[2].schema(), other.target_planet);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.quote)) {
        this.quote = data().deepCopy(fields()[3].schema(), other.quote);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.callSign)) {
        this.callSign = data().deepCopy(fields()[4].schema(), other.callSign);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.species)) {
        this.species = data().deepCopy(fields()[5].schema(), other.species);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.vehicle)) {
        this.vehicle = data().deepCopy(fields()[6].schema(), other.vehicle);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.wookieWords)) {
        this.wookieWords = data().deepCopy(fields()[7].schema(), other.wookieWords);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.alternateCharacterSpelling)) {
        this.alternateCharacterSpelling = data().deepCopy(fields()[8].schema(), other.alternateCharacterSpelling);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing StarWars instance
     * @param other The existing instance to copy.
     */
    private Builder(io.skodjob.datagenerator.models.starwars.StarWars other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.character_name)) {
        this.character_name = data().deepCopy(fields()[0].schema(), other.character_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.source_planet)) {
        this.source_planet = data().deepCopy(fields()[1].schema(), other.source_planet);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.target_planet)) {
        this.target_planet = data().deepCopy(fields()[2].schema(), other.target_planet);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.quote)) {
        this.quote = data().deepCopy(fields()[3].schema(), other.quote);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.callSign)) {
        this.callSign = data().deepCopy(fields()[4].schema(), other.callSign);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.species)) {
        this.species = data().deepCopy(fields()[5].schema(), other.species);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.vehicle)) {
        this.vehicle = data().deepCopy(fields()[6].schema(), other.vehicle);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.wookieWords)) {
        this.wookieWords = data().deepCopy(fields()[7].schema(), other.wookieWords);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.alternateCharacterSpelling)) {
        this.alternateCharacterSpelling = data().deepCopy(fields()[8].schema(), other.alternateCharacterSpelling);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'character_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getCharacterName() {
      return character_name;
    }


    /**
      * Sets the value of the 'character_name' field.
      * @param value The value of 'character_name'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder setCharacterName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.character_name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'character_name' field has been set.
      * @return True if the 'character_name' field has been set, false otherwise.
      */
    public boolean hasCharacterName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'character_name' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder clearCharacterName() {
      character_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'source_planet' field.
      * @return The value.
      */
    public java.lang.CharSequence getSourcePlanet() {
      return source_planet;
    }


    /**
      * Sets the value of the 'source_planet' field.
      * @param value The value of 'source_planet'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder setSourcePlanet(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.source_planet = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'source_planet' field has been set.
      * @return True if the 'source_planet' field has been set, false otherwise.
      */
    public boolean hasSourcePlanet() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'source_planet' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder clearSourcePlanet() {
      source_planet = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'target_planet' field.
      * @return The value.
      */
    public java.lang.CharSequence getTargetPlanet() {
      return target_planet;
    }


    /**
      * Sets the value of the 'target_planet' field.
      * @param value The value of 'target_planet'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder setTargetPlanet(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.target_planet = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'target_planet' field has been set.
      * @return True if the 'target_planet' field has been set, false otherwise.
      */
    public boolean hasTargetPlanet() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'target_planet' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder clearTargetPlanet() {
      target_planet = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'quote' field.
      * @return The value.
      */
    public java.lang.CharSequence getQuote() {
      return quote;
    }


    /**
      * Sets the value of the 'quote' field.
      * @param value The value of 'quote'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder setQuote(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.quote = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'quote' field has been set.
      * @return True if the 'quote' field has been set, false otherwise.
      */
    public boolean hasQuote() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'quote' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder clearQuote() {
      quote = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'callSign' field.
      * @return The value.
      */
    public java.lang.CharSequence getCallSign() {
      return callSign;
    }


    /**
      * Sets the value of the 'callSign' field.
      * @param value The value of 'callSign'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder setCallSign(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.callSign = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'callSign' field has been set.
      * @return True if the 'callSign' field has been set, false otherwise.
      */
    public boolean hasCallSign() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'callSign' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder clearCallSign() {
      callSign = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'species' field.
      * @return The value.
      */
    public java.lang.CharSequence getSpecies() {
      return species;
    }


    /**
      * Sets the value of the 'species' field.
      * @param value The value of 'species'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder setSpecies(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.species = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'species' field has been set.
      * @return True if the 'species' field has been set, false otherwise.
      */
    public boolean hasSpecies() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'species' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder clearSpecies() {
      species = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehicle' field.
      * @return The value.
      */
    public java.lang.CharSequence getVehicle() {
      return vehicle;
    }


    /**
      * Sets the value of the 'vehicle' field.
      * @param value The value of 'vehicle'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder setVehicle(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.vehicle = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'vehicle' field has been set.
      * @return True if the 'vehicle' field has been set, false otherwise.
      */
    public boolean hasVehicle() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'vehicle' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder clearVehicle() {
      vehicle = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'wookieWords' field.
      * @return The value.
      */
    public java.lang.CharSequence getWookieWords() {
      return wookieWords;
    }


    /**
      * Sets the value of the 'wookieWords' field.
      * @param value The value of 'wookieWords'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder setWookieWords(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.wookieWords = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'wookieWords' field has been set.
      * @return True if the 'wookieWords' field has been set, false otherwise.
      */
    public boolean hasWookieWords() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'wookieWords' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder clearWookieWords() {
      wookieWords = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'alternateCharacterSpelling' field.
      * @return The value.
      */
    public java.lang.CharSequence getAlternateCharacterSpelling() {
      return alternateCharacterSpelling;
    }


    /**
      * Sets the value of the 'alternateCharacterSpelling' field.
      * @param value The value of 'alternateCharacterSpelling'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder setAlternateCharacterSpelling(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.alternateCharacterSpelling = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'alternateCharacterSpelling' field has been set.
      * @return True if the 'alternateCharacterSpelling' field has been set, false otherwise.
      */
    public boolean hasAlternateCharacterSpelling() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'alternateCharacterSpelling' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.starwars.StarWars.Builder clearAlternateCharacterSpelling() {
      alternateCharacterSpelling = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StarWars build() {
      try {
        StarWars record = new StarWars();
        record.character_name = fieldSetFlags()[0] ? this.character_name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.source_planet = fieldSetFlags()[1] ? this.source_planet : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.target_planet = fieldSetFlags()[2] ? this.target_planet : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.quote = fieldSetFlags()[3] ? this.quote : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.callSign = fieldSetFlags()[4] ? this.callSign : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.species = fieldSetFlags()[5] ? this.species : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.vehicle = fieldSetFlags()[6] ? this.vehicle : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.wookieWords = fieldSetFlags()[7] ? this.wookieWords : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.alternateCharacterSpelling = fieldSetFlags()[8] ? this.alternateCharacterSpelling : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StarWars>
    WRITER$ = (org.apache.avro.io.DatumWriter<StarWars>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StarWars>
    READER$ = (org.apache.avro.io.DatumReader<StarWars>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.character_name);

    out.writeString(this.source_planet);

    out.writeString(this.target_planet);

    out.writeString(this.quote);

    out.writeString(this.callSign);

    out.writeString(this.species);

    out.writeString(this.vehicle);

    out.writeString(this.wookieWords);

    out.writeString(this.alternateCharacterSpelling);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.character_name = in.readString(this.character_name instanceof Utf8 ? (Utf8)this.character_name : null);

      this.source_planet = in.readString(this.source_planet instanceof Utf8 ? (Utf8)this.source_planet : null);

      this.target_planet = in.readString(this.target_planet instanceof Utf8 ? (Utf8)this.target_planet : null);

      this.quote = in.readString(this.quote instanceof Utf8 ? (Utf8)this.quote : null);

      this.callSign = in.readString(this.callSign instanceof Utf8 ? (Utf8)this.callSign : null);

      this.species = in.readString(this.species instanceof Utf8 ? (Utf8)this.species : null);

      this.vehicle = in.readString(this.vehicle instanceof Utf8 ? (Utf8)this.vehicle : null);

      this.wookieWords = in.readString(this.wookieWords instanceof Utf8 ? (Utf8)this.wookieWords : null);

      this.alternateCharacterSpelling = in.readString(this.alternateCharacterSpelling instanceof Utf8 ? (Utf8)this.alternateCharacterSpelling : null);

    } else {
      for (int i = 0; i < 9; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.character_name = in.readString(this.character_name instanceof Utf8 ? (Utf8)this.character_name : null);
          break;

        case 1:
          this.source_planet = in.readString(this.source_planet instanceof Utf8 ? (Utf8)this.source_planet : null);
          break;

        case 2:
          this.target_planet = in.readString(this.target_planet instanceof Utf8 ? (Utf8)this.target_planet : null);
          break;

        case 3:
          this.quote = in.readString(this.quote instanceof Utf8 ? (Utf8)this.quote : null);
          break;

        case 4:
          this.callSign = in.readString(this.callSign instanceof Utf8 ? (Utf8)this.callSign : null);
          break;

        case 5:
          this.species = in.readString(this.species instanceof Utf8 ? (Utf8)this.species : null);
          break;

        case 6:
          this.vehicle = in.readString(this.vehicle instanceof Utf8 ? (Utf8)this.vehicle : null);
          break;

        case 7:
          this.wookieWords = in.readString(this.wookieWords instanceof Utf8 ? (Utf8)this.wookieWords : null);
          break;

        case 8:
          this.alternateCharacterSpelling = in.readString(this.alternateCharacterSpelling instanceof Utf8 ? (Utf8)this.alternateCharacterSpelling : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










