/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.skodjob.datagenerator.models.iotdevice;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ButtonData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6315539208887626138L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ButtonData\",\"namespace\":\"io.skodjob.datagenerator.models.iotdevice\",\"fields\":[{\"name\":\"power\",\"type\":\"string\"},{\"name\":\"battery\",\"type\":{\"type\":\"record\",\"name\":\"Battery\",\"fields\":[{\"name\":\"value\",\"type\":\"int\"},{\"name\":\"unit\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ButtonData> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ButtonData> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ButtonData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ButtonData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ButtonData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ButtonData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ButtonData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ButtonData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ButtonData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence power;
  private io.skodjob.datagenerator.models.iotdevice.Battery battery;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ButtonData() {}

  /**
   * All-args constructor.
   * @param power The new value for power
   * @param battery The new value for battery
   */
  public ButtonData(java.lang.CharSequence power, io.skodjob.datagenerator.models.iotdevice.Battery battery) {
    this.power = power;
    this.battery = battery;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return power;
    case 1: return battery;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: power = (java.lang.CharSequence)value$; break;
    case 1: battery = (io.skodjob.datagenerator.models.iotdevice.Battery)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'power' field.
   * @return The value of the 'power' field.
   */
  public java.lang.CharSequence getPower() {
    return power;
  }


  /**
   * Sets the value of the 'power' field.
   * @param value the value to set.
   */
  public void setPower(java.lang.CharSequence value) {
    this.power = value;
  }

  /**
   * Gets the value of the 'battery' field.
   * @return The value of the 'battery' field.
   */
  public io.skodjob.datagenerator.models.iotdevice.Battery getBattery() {
    return battery;
  }


  /**
   * Sets the value of the 'battery' field.
   * @param value the value to set.
   */
  public void setBattery(io.skodjob.datagenerator.models.iotdevice.Battery value) {
    this.battery = value;
  }

  /**
   * Creates a new ButtonData RecordBuilder.
   * @return A new ButtonData RecordBuilder
   */
  public static io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder newBuilder() {
    return new io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder();
  }

  /**
   * Creates a new ButtonData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ButtonData RecordBuilder
   */
  public static io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder newBuilder(io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder other) {
    if (other == null) {
      return new io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder();
    } else {
      return new io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder(other);
    }
  }

  /**
   * Creates a new ButtonData RecordBuilder by copying an existing ButtonData instance.
   * @param other The existing instance to copy.
   * @return A new ButtonData RecordBuilder
   */
  public static io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder newBuilder(io.skodjob.datagenerator.models.iotdevice.ButtonData other) {
    if (other == null) {
      return new io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder();
    } else {
      return new io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder(other);
    }
  }

  /**
   * RecordBuilder for ButtonData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ButtonData>
    implements org.apache.avro.data.RecordBuilder<ButtonData> {

    private java.lang.CharSequence power;
    private io.skodjob.datagenerator.models.iotdevice.Battery battery;
    private io.skodjob.datagenerator.models.iotdevice.Battery.Builder batteryBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.power)) {
        this.power = data().deepCopy(fields()[0].schema(), other.power);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.battery)) {
        this.battery = data().deepCopy(fields()[1].schema(), other.battery);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasBatteryBuilder()) {
        this.batteryBuilder = io.skodjob.datagenerator.models.iotdevice.Battery.newBuilder(other.getBatteryBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing ButtonData instance
     * @param other The existing instance to copy.
     */
    private Builder(io.skodjob.datagenerator.models.iotdevice.ButtonData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.power)) {
        this.power = data().deepCopy(fields()[0].schema(), other.power);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.battery)) {
        this.battery = data().deepCopy(fields()[1].schema(), other.battery);
        fieldSetFlags()[1] = true;
      }
      this.batteryBuilder = null;
    }

    /**
      * Gets the value of the 'power' field.
      * @return The value.
      */
    public java.lang.CharSequence getPower() {
      return power;
    }


    /**
      * Sets the value of the 'power' field.
      * @param value The value of 'power'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder setPower(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.power = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'power' field has been set.
      * @return True if the 'power' field has been set, false otherwise.
      */
    public boolean hasPower() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'power' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder clearPower() {
      power = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'battery' field.
      * @return The value.
      */
    public io.skodjob.datagenerator.models.iotdevice.Battery getBattery() {
      return battery;
    }


    /**
      * Sets the value of the 'battery' field.
      * @param value The value of 'battery'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder setBattery(io.skodjob.datagenerator.models.iotdevice.Battery value) {
      validate(fields()[1], value);
      this.batteryBuilder = null;
      this.battery = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'battery' field has been set.
      * @return True if the 'battery' field has been set, false otherwise.
      */
    public boolean hasBattery() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'battery' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public io.skodjob.datagenerator.models.iotdevice.Battery.Builder getBatteryBuilder() {
      if (batteryBuilder == null) {
        if (hasBattery()) {
          setBatteryBuilder(io.skodjob.datagenerator.models.iotdevice.Battery.newBuilder(battery));
        } else {
          setBatteryBuilder(io.skodjob.datagenerator.models.iotdevice.Battery.newBuilder());
        }
      }
      return batteryBuilder;
    }

    /**
     * Sets the Builder instance for the 'battery' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder setBatteryBuilder(io.skodjob.datagenerator.models.iotdevice.Battery.Builder value) {
      clearBattery();
      batteryBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'battery' field has an active Builder instance
     * @return True if the 'battery' field has an active Builder instance
     */
    public boolean hasBatteryBuilder() {
      return batteryBuilder != null;
    }

    /**
      * Clears the value of the 'battery' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.ButtonData.Builder clearBattery() {
      battery = null;
      batteryBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ButtonData build() {
      try {
        ButtonData record = new ButtonData();
        record.power = fieldSetFlags()[0] ? this.power : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (batteryBuilder != null) {
          try {
            record.battery = this.batteryBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("battery"));
            throw e;
          }
        } else {
          record.battery = fieldSetFlags()[1] ? this.battery : (io.skodjob.datagenerator.models.iotdevice.Battery) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ButtonData>
    WRITER$ = (org.apache.avro.io.DatumWriter<ButtonData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ButtonData>
    READER$ = (org.apache.avro.io.DatumReader<ButtonData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.power);

    this.battery.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.power = in.readString(this.power instanceof Utf8 ? (Utf8)this.power : null);

      if (this.battery == null) {
        this.battery = new io.skodjob.datagenerator.models.iotdevice.Battery();
      }
      this.battery.customDecode(in);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.power = in.readString(this.power instanceof Utf8 ? (Utf8)this.power : null);
          break;

        case 1:
          if (this.battery == null) {
            this.battery = new io.skodjob.datagenerator.models.iotdevice.Battery();
          }
          this.battery.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










