/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.skodjob.datagenerator.models.iotdevice;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LightData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2564045829790584903L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LightData\",\"namespace\":\"io.skodjob.datagenerator.models.iotdevice\",\"fields\":[{\"name\":\"power\",\"type\":\"string\"},{\"name\":\"brightness\",\"type\":\"int\"},{\"name\":\"power_on_behavior\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LightData> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LightData> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LightData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LightData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LightData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LightData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LightData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LightData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LightData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence power;
  private int brightness;
  private java.lang.CharSequence power_on_behavior;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LightData() {}

  /**
   * All-args constructor.
   * @param power The new value for power
   * @param brightness The new value for brightness
   * @param power_on_behavior The new value for power_on_behavior
   */
  public LightData(java.lang.CharSequence power, java.lang.Integer brightness, java.lang.CharSequence power_on_behavior) {
    this.power = power;
    this.brightness = brightness;
    this.power_on_behavior = power_on_behavior;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return power;
    case 1: return brightness;
    case 2: return power_on_behavior;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: power = (java.lang.CharSequence)value$; break;
    case 1: brightness = (java.lang.Integer)value$; break;
    case 2: power_on_behavior = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'power' field.
   * @return The value of the 'power' field.
   */
  public java.lang.CharSequence getPower() {
    return power;
  }


  /**
   * Sets the value of the 'power' field.
   * @param value the value to set.
   */
  public void setPower(java.lang.CharSequence value) {
    this.power = value;
  }

  /**
   * Gets the value of the 'brightness' field.
   * @return The value of the 'brightness' field.
   */
  public int getBrightness() {
    return brightness;
  }


  /**
   * Sets the value of the 'brightness' field.
   * @param value the value to set.
   */
  public void setBrightness(int value) {
    this.brightness = value;
  }

  /**
   * Gets the value of the 'power_on_behavior' field.
   * @return The value of the 'power_on_behavior' field.
   */
  public java.lang.CharSequence getPowerOnBehavior() {
    return power_on_behavior;
  }


  /**
   * Sets the value of the 'power_on_behavior' field.
   * @param value the value to set.
   */
  public void setPowerOnBehavior(java.lang.CharSequence value) {
    this.power_on_behavior = value;
  }

  /**
   * Creates a new LightData RecordBuilder.
   * @return A new LightData RecordBuilder
   */
  public static io.skodjob.datagenerator.models.iotdevice.LightData.Builder newBuilder() {
    return new io.skodjob.datagenerator.models.iotdevice.LightData.Builder();
  }

  /**
   * Creates a new LightData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LightData RecordBuilder
   */
  public static io.skodjob.datagenerator.models.iotdevice.LightData.Builder newBuilder(io.skodjob.datagenerator.models.iotdevice.LightData.Builder other) {
    if (other == null) {
      return new io.skodjob.datagenerator.models.iotdevice.LightData.Builder();
    } else {
      return new io.skodjob.datagenerator.models.iotdevice.LightData.Builder(other);
    }
  }

  /**
   * Creates a new LightData RecordBuilder by copying an existing LightData instance.
   * @param other The existing instance to copy.
   * @return A new LightData RecordBuilder
   */
  public static io.skodjob.datagenerator.models.iotdevice.LightData.Builder newBuilder(io.skodjob.datagenerator.models.iotdevice.LightData other) {
    if (other == null) {
      return new io.skodjob.datagenerator.models.iotdevice.LightData.Builder();
    } else {
      return new io.skodjob.datagenerator.models.iotdevice.LightData.Builder(other);
    }
  }

  /**
   * RecordBuilder for LightData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LightData>
    implements org.apache.avro.data.RecordBuilder<LightData> {

    private java.lang.CharSequence power;
    private int brightness;
    private java.lang.CharSequence power_on_behavior;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.skodjob.datagenerator.models.iotdevice.LightData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.power)) {
        this.power = data().deepCopy(fields()[0].schema(), other.power);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.brightness)) {
        this.brightness = data().deepCopy(fields()[1].schema(), other.brightness);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.power_on_behavior)) {
        this.power_on_behavior = data().deepCopy(fields()[2].schema(), other.power_on_behavior);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing LightData instance
     * @param other The existing instance to copy.
     */
    private Builder(io.skodjob.datagenerator.models.iotdevice.LightData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.power)) {
        this.power = data().deepCopy(fields()[0].schema(), other.power);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.brightness)) {
        this.brightness = data().deepCopy(fields()[1].schema(), other.brightness);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.power_on_behavior)) {
        this.power_on_behavior = data().deepCopy(fields()[2].schema(), other.power_on_behavior);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'power' field.
      * @return The value.
      */
    public java.lang.CharSequence getPower() {
      return power;
    }


    /**
      * Sets the value of the 'power' field.
      * @param value The value of 'power'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.LightData.Builder setPower(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.power = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'power' field has been set.
      * @return True if the 'power' field has been set, false otherwise.
      */
    public boolean hasPower() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'power' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.LightData.Builder clearPower() {
      power = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'brightness' field.
      * @return The value.
      */
    public int getBrightness() {
      return brightness;
    }


    /**
      * Sets the value of the 'brightness' field.
      * @param value The value of 'brightness'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.LightData.Builder setBrightness(int value) {
      validate(fields()[1], value);
      this.brightness = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'brightness' field has been set.
      * @return True if the 'brightness' field has been set, false otherwise.
      */
    public boolean hasBrightness() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'brightness' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.LightData.Builder clearBrightness() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'power_on_behavior' field.
      * @return The value.
      */
    public java.lang.CharSequence getPowerOnBehavior() {
      return power_on_behavior;
    }


    /**
      * Sets the value of the 'power_on_behavior' field.
      * @param value The value of 'power_on_behavior'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.LightData.Builder setPowerOnBehavior(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.power_on_behavior = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'power_on_behavior' field has been set.
      * @return True if the 'power_on_behavior' field has been set, false otherwise.
      */
    public boolean hasPowerOnBehavior() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'power_on_behavior' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.LightData.Builder clearPowerOnBehavior() {
      power_on_behavior = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LightData build() {
      try {
        LightData record = new LightData();
        record.power = fieldSetFlags()[0] ? this.power : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.brightness = fieldSetFlags()[1] ? this.brightness : (java.lang.Integer) defaultValue(fields()[1]);
        record.power_on_behavior = fieldSetFlags()[2] ? this.power_on_behavior : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LightData>
    WRITER$ = (org.apache.avro.io.DatumWriter<LightData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LightData>
    READER$ = (org.apache.avro.io.DatumReader<LightData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.power);

    out.writeInt(this.brightness);

    out.writeString(this.power_on_behavior);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.power = in.readString(this.power instanceof Utf8 ? (Utf8)this.power : null);

      this.brightness = in.readInt();

      this.power_on_behavior = in.readString(this.power_on_behavior instanceof Utf8 ? (Utf8)this.power_on_behavior : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.power = in.readString(this.power instanceof Utf8 ? (Utf8)this.power : null);
          break;

        case 1:
          this.brightness = in.readInt();
          break;

        case 2:
          this.power_on_behavior = in.readString(this.power_on_behavior instanceof Utf8 ? (Utf8)this.power_on_behavior : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










