/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.skodjob.datagenerator.models.iotdevice;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ThermometerData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4268847101870090241L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ThermometerData\",\"namespace\":\"io.skodjob.datagenerator.models.iotdevice\",\"fields\":[{\"name\":\"temperature\",\"type\":\"float\"},{\"name\":\"humidity\",\"type\":\"float\"},{\"name\":\"battery\",\"type\":{\"type\":\"record\",\"name\":\"Battery\",\"fields\":[{\"name\":\"value\",\"type\":\"int\"},{\"name\":\"unit\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ThermometerData> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ThermometerData> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ThermometerData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ThermometerData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ThermometerData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ThermometerData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ThermometerData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ThermometerData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ThermometerData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private float temperature;
  private float humidity;
  private io.skodjob.datagenerator.models.iotdevice.Battery battery;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ThermometerData() {}

  /**
   * All-args constructor.
   * @param temperature The new value for temperature
   * @param humidity The new value for humidity
   * @param battery The new value for battery
   */
  public ThermometerData(java.lang.Float temperature, java.lang.Float humidity, io.skodjob.datagenerator.models.iotdevice.Battery battery) {
    this.temperature = temperature;
    this.humidity = humidity;
    this.battery = battery;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return temperature;
    case 1: return humidity;
    case 2: return battery;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: temperature = (java.lang.Float)value$; break;
    case 1: humidity = (java.lang.Float)value$; break;
    case 2: battery = (io.skodjob.datagenerator.models.iotdevice.Battery)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'temperature' field.
   * @return The value of the 'temperature' field.
   */
  public float getTemperature() {
    return temperature;
  }


  /**
   * Sets the value of the 'temperature' field.
   * @param value the value to set.
   */
  public void setTemperature(float value) {
    this.temperature = value;
  }

  /**
   * Gets the value of the 'humidity' field.
   * @return The value of the 'humidity' field.
   */
  public float getHumidity() {
    return humidity;
  }


  /**
   * Sets the value of the 'humidity' field.
   * @param value the value to set.
   */
  public void setHumidity(float value) {
    this.humidity = value;
  }

  /**
   * Gets the value of the 'battery' field.
   * @return The value of the 'battery' field.
   */
  public io.skodjob.datagenerator.models.iotdevice.Battery getBattery() {
    return battery;
  }


  /**
   * Sets the value of the 'battery' field.
   * @param value the value to set.
   */
  public void setBattery(io.skodjob.datagenerator.models.iotdevice.Battery value) {
    this.battery = value;
  }

  /**
   * Creates a new ThermometerData RecordBuilder.
   * @return A new ThermometerData RecordBuilder
   */
  public static io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder newBuilder() {
    return new io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder();
  }

  /**
   * Creates a new ThermometerData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ThermometerData RecordBuilder
   */
  public static io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder newBuilder(io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder other) {
    if (other == null) {
      return new io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder();
    } else {
      return new io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder(other);
    }
  }

  /**
   * Creates a new ThermometerData RecordBuilder by copying an existing ThermometerData instance.
   * @param other The existing instance to copy.
   * @return A new ThermometerData RecordBuilder
   */
  public static io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder newBuilder(io.skodjob.datagenerator.models.iotdevice.ThermometerData other) {
    if (other == null) {
      return new io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder();
    } else {
      return new io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder(other);
    }
  }

  /**
   * RecordBuilder for ThermometerData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ThermometerData>
    implements org.apache.avro.data.RecordBuilder<ThermometerData> {

    private float temperature;
    private float humidity;
    private io.skodjob.datagenerator.models.iotdevice.Battery battery;
    private io.skodjob.datagenerator.models.iotdevice.Battery.Builder batteryBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.temperature)) {
        this.temperature = data().deepCopy(fields()[0].schema(), other.temperature);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.humidity)) {
        this.humidity = data().deepCopy(fields()[1].schema(), other.humidity);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.battery)) {
        this.battery = data().deepCopy(fields()[2].schema(), other.battery);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasBatteryBuilder()) {
        this.batteryBuilder = io.skodjob.datagenerator.models.iotdevice.Battery.newBuilder(other.getBatteryBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing ThermometerData instance
     * @param other The existing instance to copy.
     */
    private Builder(io.skodjob.datagenerator.models.iotdevice.ThermometerData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.temperature)) {
        this.temperature = data().deepCopy(fields()[0].schema(), other.temperature);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.humidity)) {
        this.humidity = data().deepCopy(fields()[1].schema(), other.humidity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.battery)) {
        this.battery = data().deepCopy(fields()[2].schema(), other.battery);
        fieldSetFlags()[2] = true;
      }
      this.batteryBuilder = null;
    }

    /**
      * Gets the value of the 'temperature' field.
      * @return The value.
      */
    public float getTemperature() {
      return temperature;
    }


    /**
      * Sets the value of the 'temperature' field.
      * @param value The value of 'temperature'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder setTemperature(float value) {
      validate(fields()[0], value);
      this.temperature = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'temperature' field has been set.
      * @return True if the 'temperature' field has been set, false otherwise.
      */
    public boolean hasTemperature() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'temperature' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder clearTemperature() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'humidity' field.
      * @return The value.
      */
    public float getHumidity() {
      return humidity;
    }


    /**
      * Sets the value of the 'humidity' field.
      * @param value The value of 'humidity'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder setHumidity(float value) {
      validate(fields()[1], value);
      this.humidity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'humidity' field has been set.
      * @return True if the 'humidity' field has been set, false otherwise.
      */
    public boolean hasHumidity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'humidity' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder clearHumidity() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'battery' field.
      * @return The value.
      */
    public io.skodjob.datagenerator.models.iotdevice.Battery getBattery() {
      return battery;
    }


    /**
      * Sets the value of the 'battery' field.
      * @param value The value of 'battery'.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder setBattery(io.skodjob.datagenerator.models.iotdevice.Battery value) {
      validate(fields()[2], value);
      this.batteryBuilder = null;
      this.battery = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'battery' field has been set.
      * @return True if the 'battery' field has been set, false otherwise.
      */
    public boolean hasBattery() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'battery' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public io.skodjob.datagenerator.models.iotdevice.Battery.Builder getBatteryBuilder() {
      if (batteryBuilder == null) {
        if (hasBattery()) {
          setBatteryBuilder(io.skodjob.datagenerator.models.iotdevice.Battery.newBuilder(battery));
        } else {
          setBatteryBuilder(io.skodjob.datagenerator.models.iotdevice.Battery.newBuilder());
        }
      }
      return batteryBuilder;
    }

    /**
     * Sets the Builder instance for the 'battery' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder setBatteryBuilder(io.skodjob.datagenerator.models.iotdevice.Battery.Builder value) {
      clearBattery();
      batteryBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'battery' field has an active Builder instance
     * @return True if the 'battery' field has an active Builder instance
     */
    public boolean hasBatteryBuilder() {
      return batteryBuilder != null;
    }

    /**
      * Clears the value of the 'battery' field.
      * @return This builder.
      */
    public io.skodjob.datagenerator.models.iotdevice.ThermometerData.Builder clearBattery() {
      battery = null;
      batteryBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ThermometerData build() {
      try {
        ThermometerData record = new ThermometerData();
        record.temperature = fieldSetFlags()[0] ? this.temperature : (java.lang.Float) defaultValue(fields()[0]);
        record.humidity = fieldSetFlags()[1] ? this.humidity : (java.lang.Float) defaultValue(fields()[1]);
        if (batteryBuilder != null) {
          try {
            record.battery = this.batteryBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("battery"));
            throw e;
          }
        } else {
          record.battery = fieldSetFlags()[2] ? this.battery : (io.skodjob.datagenerator.models.iotdevice.Battery) defaultValue(fields()[2]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ThermometerData>
    WRITER$ = (org.apache.avro.io.DatumWriter<ThermometerData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ThermometerData>
    READER$ = (org.apache.avro.io.DatumReader<ThermometerData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeFloat(this.temperature);

    out.writeFloat(this.humidity);

    this.battery.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.temperature = in.readFloat();

      this.humidity = in.readFloat();

      if (this.battery == null) {
        this.battery = new io.skodjob.datagenerator.models.iotdevice.Battery();
      }
      this.battery.customDecode(in);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.temperature = in.readFloat();
          break;

        case 1:
          this.humidity = in.readFloat();
          break;

        case 2:
          if (this.battery == null) {
            this.battery = new io.skodjob.datagenerator.models.iotdevice.Battery();
          }
          this.battery.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










